<a href="https://colab.research.google.com/github/sidcodes2727/ML-labs/blob/main/MLlab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub
path = kagglehub.dataset_download("uciml/mushroom-classification")
path

Using Colab cache for faster access to the 'mushroom-classification' dataset.

'/kaggle/input/mushroom-classification'

In [ ]:
import pandas as pd
df = pd.read_csv("/kaggle/input/mushroom-classification/mushrooms.csv")
print(df.columns)
print(df.duplicated().sum())
for c in df.columns:
    print(c)
    print(df[c].unique())
    print()
df

Index(['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')
0
class
['p' 'e']

cap-shape
['x' 'b' 's' 'f' 'k' 'c']

cap-surface
['s' 'y' 'f' 'g']

cap-color
['n' 'y' 'w' 'g' 'e' 'p' 'b' 'u' 'c' 'r']

bruises
['t' 'f']

odor
['p' 'a' 'l' 'n' 'f' 'c' 'y' 's' 'm']

gill-attachment
['f' 'a']

gill-spacing
['c' 'w']

gill-size
['n' 'b']

gill-color
['k' 'n' 'g' 'p' 'w' 'h' 'u' 'e' 'b' 'r' 'y' 'o']

stalk-shape
['e' 't']

stalk-root
['e' 'c' 'b' 'r' '?']

stalk-surface-above-ring
['s' 'f' 'k' 'y']

stalk-surface-below-ring
['s' 'f' 'y' 'k']

stalk-color-above-ring
['w' 'g' 'p' 'n' 'b' 'e' 'o' 'c' 'y']

stalk-color-below-ring
['w' 'p' 'g' 'b' 'n' 'e' 'y' 'o' 'c']

veil-type
['p']

veil-color
['w' 'n' 'o' 'y']

ring-number
['o' 't' 'n']

ring-type
['p' 'e' 'l' 'f' 'n']

spore-print-color
['k' 'n' 'u' 'h' 'w' 'r' 'o' 'y' 'b']

population
['s' 'n' 'a' 'v' 'y' 'c']

habitat
['u' 'g' 'm' 'd' 'p' 'w' 'l']

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,e,k,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,b,c,l
8120,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,n,o,p,b,v,l
8121,e,f,s,n,f,n,a,c,b,n,...,s,o,o,p,o,o,p,b,c,l
8122,p,k,y,n,f,y,f,c,n,b,...,k,w,w,p,w,o,e,w,v,l
8123,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,o,c,l

In [ ]:
df["class"].value_counts()

class
e    4208
p    3916
Name: count, dtype: int64

In [ ]:
print(df["stalk-root"].mode())
req = df['stalk-root'].mode()[0]
df['stalk-root'] = df['stalk-root'].replace('?', req)
print(df['stalk-root'].unique())

0    b
Name: stalk-root, dtype: object
['e' 'c' 'b' 'r']

In [ ]:
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
for col in df.columns:
    df[col] = enc.fit_transform(df[col])
df

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,1,5,2,4,1,6,1,0,1,4,...,2,7,7,0,2,1,4,2,3,5
1,0,5,2,9,1,0,1,0,0,4,...,2,7,7,0,2,1,4,3,2,1
2,0,0,2,8,1,3,1,0,0,5,...,2,7,7,0,2,1,4,3,2,3
3,1,5,3,8,1,6,1,0,1,5,...,2,7,7,0,2,1,4,2,3,5
4,0,5,2,3,0,5,1,1,0,4,...,2,7,7,0,2,1,0,3,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,0,3,2,4,0,5,0,0,0,11,...,2,5,5,0,1,1,4,0,1,2
8120,0,5,2,4,0,5,0,0,0,11,...,2,5,5,0,0,1,4,0,4,2
8121,0,2,2,4,0,5,0,0,0,5,...,2,5,5,0,1,1,4,0,1,2
8122,1,3,3,4,0,8,1,0,1,0,...,1,7,7,0,2,1,0,7,4,2
8123,0,5,2,4,0,5,0,0,0,11,...,2,5,5,0,1,1,4,4,1,2

In [ ]:
from sklearn.model_selection import train_test_split
X= df.drop(columns=['class'])
y= df['class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(5686, 22)
(2438, 22)
(5686,)
(2438,)

In [ ]:
import numpy as np
def entropy(fea):
  # fea.value_counts()
  cnts= fea.value_counts()
  tot= len(fea)
  req= 0;
  for i in cnts:
    p=i/tot
    req=req-p*np.log2(p)

  return req
# entropy(df['class'])

In [ ]:
def infoGain(data, fea):
  parentEntropy = entropy(data['class'])
  sumchildEntropy = 0
  for i in data[fea].unique():
    req = data[data[fea] == i]
    prop = len(req)/len(data)
    sumchildEntropy+= prop* entropy(req['class'])

  return parentEntropy - sumchildEntropy

In [ ]:
def gainRatio(data, fea):
  gain= infoGain(data, fea)
  splitInfo=0
  for i in data[fea].unique():
    req= data[data[fea] == i]
    prop= len(req)/len(data)
    splitInfo= splitInfo -prop*np.log2(prop)

  if splitInfo==0:  return 0

  r = gain/splitInfo
  return r

In [ ]:
def giniIdx(fea):
  cnts= fea.value_counts()
  tot= len(fea)
  req= 1;
  for i in cnts:
    p=i/tot
    req-=p*p

  return req

In [ ]:
def giniGain(data,fea):
  parentGini = giniIdx(data['class'])
  sumChildGini= 0
  for i in data[fea].unique():
    req= data[data[fea] == i]
    prop= len(req)/len(data)
    sumChildGini+= prop* giniIdx(req['class'])

  return parentGini-sumChildGini

In [ ]:
def miscError(fea):
  cnts= fea.value_counts()
  tot= len(fea)
  mx= 0
  for i in cnts:
    mx= max(mx,i)

  return 1-(mx/tot)

In [ ]:
def miscGain(data, fea):
  parentMisc = miscError(data['class'])
  sumChildMisc= 0
  for i in data[fea].unique():
    req = data[data[fea] == i]
    prop= len(req)/len(data)
    sumChildMisc+=prop* miscError(req['class'])
  return parentMisc- sumChildMisc

In [ ]:
def id3(data, features, func):
    if entropy(data['class'])==0: return data['class'].iloc[0]

    if len(features)==0:  return data['class'].mode()[0]
    gains=[]

    for f in features:
        temp = func(data,f)
        print(f"{f} :", temp)
        gains.append(temp)

    idx= np.argmax(gains)
    bestFeature= features[idx]
    print(f"best feature - ", bestFeature)
    print()
    tree = {bestFeature:{}}

    remFeatures= []
    for f in features:
      if f!=bestFeature:
        remFeatures.append(f)

    for val in data[bestFeature].unique():
        filter= data[data[bestFeature]==val]
        tree[bestFeature][val]= id3(filter,remFeatures,func)

    return tree

In [ ]:
def predict(query, tree):

    for node in tree.keys():
        value= query[node]
        res= tree[node][value]

        if isinstance(res,dict):
            return predict(query, res)
        else:
            return res

In [ ]:
train_df = X_train.copy()
train_df["class"] = y_train
features = list(X_train.columns)

In [ ]:
print("InfoGain:\n")
dt1= id3(train_df, features, infoGain)
print("gainratior:\n")
dt2= id3(train_df, features, gainRatio)
print("Gini Index:\n")
dt3= id3(train_df, features, giniGain)
print("miscError:\n")
dt4= id3(train_df, features, miscGain)

InfoGain:

cap-shape : 0.05026181677784336
cap-surface : 0.029993500744027957
cap-color : 0.03715134795590169
bruises : 0.19562130040685044
odor : 0.9093433988101001
gill-attachment : 0.012828944006453957
gill-spacing : 0.09841133047099693
gill-size : 0.22930715895323128
gill-color : 0.4215392248774176
stalk-shape : 0.008215427755146387
stalk-root : 0.10792419262982034
stalk-surface-above-ring : 0.28271455345699603
stalk-surface-below-ring : 0.2718066794111724
stalk-color-above-ring : 0.25596432726103535
stalk-color-below-ring : 0.2382873074893208
veil-type : 0.0
veil-color : 0.02254515656238676
ring-number : 0.039761333724610104
ring-type : 0.3209170949231932
spore-print-color : 0.48005539828822097
population : 0.20307012642232658
habitat : 0.15605510102269582
best feature -  odor

cap-shape : 0.03634669035902857
cap-surface : 0.01857633415197399
cap-color : 0.09427265442711387
bruises : 0.0004899353374851201
gill-attachment : 0.002506403960969794
gill-spacing : 0.003507739628592993
gill-size : 0.025196614460909955
gill-color : 0.08457433398997201
stalk-shape : 0.060152343276611814
stalk-root : 0.02436495555408899
stalk-surface-above-ring : 0.023806677784544927
stalk-surface-below-ring : 0.05031136798860744
stalk-color-above-ring : 0.036093833043062545
stalk-color-below-ring : 0.059584821017576506
veil-type : 0.0
veil-color : 0.014468736885409228
ring-number : 0.020547532086396897
ring-type : 0.0009752401097502805
spore-print-color : 0.13637285516789047
population : 0.04174444897902807
habitat : 0.055562145824766346
best feature -  spore-print-color

cap-shape : 0.030926788663871496
cap-surface : 0.10830666427920604
cap-color : 0.21752573190557595
bruises : 0.01058638315844218
gill-attachment : 0.0
gill-spacing : 0.011169950244641402
gill-size : 0.24081352340581533
gill-color : 0.0882085390051689
stalk-shape : 0.0
stalk-root : 0.05223180909999309
stalk-surface-above-ring : 0.06830201837870226
stalk-surface-below-ring : 0.2137594112644403
stalk-color-above-ring : 0.07128883068182745
stalk-color-below-ring : 0.19955043722777813
veil-type : 0.0
veil-color : 0.05223180909999309
ring-number : 0.24081352340581533
ring-type : 0.03726356350285448
population : 0.12039685973649583
habitat : 0.2651869785611154
best feature -  habitat

cap-shape : 0.028321923854302766
cap-surface : 0.3844965768075451
cap-color : 0.18112551715329472
bruises : 0.0
gill-attachment : 0.0
gill-spacing : 0.0
gill-size : 0.691289869405789
gill-color : 0.0
stalk-shape : 0.0
stalk-root : 0.0
stalk-surface-above-ring : 0.691289869405789
stalk-surface-below-ring : 0.0
stalk-color-above-ring : 0.691289869405789
stalk-color-below-ring : 0.14100550577004511
veil-type : 0.0
veil-color : 0.0
ring-number : 0.691289869405789
ring-type : 0.691289869405789
population : 0.691289869405789
best feature -  gill-size

cap-shape : 0.41282921884166046
cap-surface : 0.3602281629370891
cap-color : 0.8366407419411672
bruises : 0.2998428398862386
gill-attachment : 0.0
gill-spacing : 0.0
gill-size : 0.0
gill-color : 0.13701850183231923
stalk-shape : 0.0
stalk-root : 0.2998428398862386
stalk-surface-above-ring : 0.40395907556296307
stalk-surface-below-ring : 0.42335806181464275
stalk-color-above-ring : 0.2998428398862386
stalk-color-below-ring : 0.8366407419411672
veil-type : 0.0
veil-color : 0.2998428398862386
ring-number : 0.0
ring-type : 0.2998428398862386
population : 0.8366407419411672
best feature -  cap-color

gainratior:

cap-shape : 0.03064656865136021
cap-surface : 0.01901239542471256
cap-color : 0.01482491186945626
bruises : 0.19948823656185713
odor : 0.39299571106456027
gill-attachment : 0.07697759571316551
gill-spacing : 0.15440776844172827
gill-size : 0.257717332442167
gill-color : 0.13931890432773308
stalk-shape : 0.008327076664209154
stalk-root : 0.10046681070402004
stalk-surface-above-ring : 0.23241951665122507
stalk-surface-below-ring : 0.19413730632527093
stalk-color-above-ring : 0.13184872612708506
stalk-color-below-ring : 0.12077365069668887
veil-type : 0
veil-color : 0.11954425595549717
ring-number : 0.09562753837352246
ring-type : 0.2091037725936983
spore-print-color : 0.21817699867666102
population : 0.10179402795620059
habitat : 0.06878378576474851
best feature -  odor

cap-shape : 0.022741878345628932
cap-surface : 0.011896945590007453
cap-color : 0.04125344577159234
bruises : 0.0004992722077153495
gill-attachment : 0.0085748080581852
gill-spacing : 0.0038972616807987767
gill-size : 0.07060997540272869
gill-color : 0.029570166497376996
stalk-shape : 0.0694775505178061
stalk-root : 0.029641782212449293
stalk-surface-above-ring : 0.028242865342562467
stalk-surface-below-ring : 0.055330859925652794
stalk-color-above-ring : 0.02075981950897537
stalk-color-below-ring : 0.0319675834876179
veil-type : 0
veil-color : 0.039312743880751344
ring-number : 0.03137723561932462
ring-type : 0.001001066888219006
spore-print-color : 0.07018371934817783
population : 0.0182440179038184
habitat : 0.031119059142377205
best feature -  gill-size

cap-shape : 0.021392329947429612
cap-surface : 0.010576988116488644
cap-color : 0.03084339250390016
bruises : 0.014567533335085854
gill-attachment : 0.005361701375186901
gill-spacing : 0.012417068483579822
gill-color : 0.02757962942090503
stalk-shape : 0.05395106828056747
stalk-root : 0.009824296411566525
stalk-surface-above-ring : 0.006361577351021148
stalk-surface-below-ring : 0.006460081041733321
stalk-color-above-ring : 0.009753969969696397
stalk-color-below-ring : 0.009725484935720076
veil-type : 0
veil-color : 0.004548049328289847
ring-number : 0.07416175460989753
ring-type : 0.011464845179821638
spore-print-color : 0.07611304855504238
population : 0.014529886527823898
habitat : 0.04715961655196571
best feature -  spore-print-color

cap-shape : 0.11832369779951263
cap-surface : 0.0827074669400293
cap-color : 0.1577433847352498
bruises : 0.38704013852837493
gill-attachment : 0
gill-spacing : 0.0074549685265579745
gill-color : 0.1200473745485
stalk-shape : 0
stalk-root : 0.19668805749786863
stalk-surface-above-ring : 0.43867564131143155
stalk-surface-below-ring : 0.3737007315848223
stalk-color-above-ring : 0.38704013852837493
stalk-color-below-ring : 0.24350000327702956
veil-type : 0
veil-color : 0.38704013852837493
ring-number : 0
ring-type : 0.1229877607858906
spore-print-color : 0.17125771378227253
population : 0.2159102475413309
habitat : 0.11167672037606406
best feature -  stalk-surface-above-ring

cap-shape : 0.0932020620603613
cap-surface : 0.1619321007067967
cap-color : 0.06423530764270699
bruises : 1.0
gill-attachment : 0
gill-spacing : 0.17279600585694085
gill-color : 0.03549535025367101
stalk-shape : 0
stalk-root : 0.05389999335082417
stalk-surface-below-ring : 0.033637533337847934
stalk-color-above-ring : 0
stalk-color-below-ring : 0.018818805407131354
veil-type : 0
veil-color : 0
ring-number : 0
ring-type : 0.029165322859696977
spore-print-color : 0.06189068467495593
population : 0.2315479406837389
habitat : 0.08377169987807426
best feature -  bruises

Gini Index:

cap-shape : 0.030745895829415615
cap-surface : 0.02025700650209189
cap-color : 0.02445089153739921
bruises : 0.12759301924210703
odor : 0.47203676623345847
gill-attachment : 0.007599431355352904
gill-spacing : 0.059244524467826076
gill-size : 0.1451034563442699
gill-color : 0.23461217111047056
stalk-shape : 0.0056787401955996075
stalk-root : 0.06458267194474382
stalk-surface-above-ring : 0.17161796299800203
stalk-surface-below-ring : 0.16478585000863666
stalk-color-above-ring : 0.13898291539769392
stalk-color-below-ring : 0.13039149309389847
veil-type : 0.0
veil-color : 0.011109420239629242
ring-number : 0.0236795914907163
ring-type : 0.18335057301415647
spore-print-color : 0.2825533077691109
population : 0.1195567921910562
habitat : 0.096596550938858
best feature -  odor

cap-shape : 0.006610291195096062
cap-surface : 0.0038224981304983002
cap-color : 0.021904195894311904
bruises : 4.177828663512462e-05
gill-attachment : 0.0001135822826638655
gill-spacing : 0.00026744569764990817
gill-size : 0.004249707770142011
gill-color : 0.01718724837897636
stalk-shape : 0.005189285271850107
stalk-root : 0.005133956417376601
stalk-surface-above-ring : 0.0036614595041074977
stalk-surface-below-ring : 0.014470133515558911
stalk-color-above-ring : 0.0058551014406949126
stalk-color-below-ring : 0.014449319622949972
veil-type : 0.0
veil-color : 0.00465570884732712
ring-number : 0.0024662891910247203
ring-type : 5.7119955514550735e-05
spore-print-color : 0.03727173200323963
population : 0.0029408958672547045
habitat : 0.018065252411897187
best feature -  spore-print-color

cap-shape : 0.01270872764614181
cap-surface : 0.026591509182478157
cap-color : 0.07728572476803516
bruises : 0.0018934154695282313
gill-attachment : 0.0
gill-spacing : 0.0022317085659831204
gill-size : 0.06673270290817772
gill-color : 0.01970531097669137
stalk-shape : 0.0
stalk-root : 0.023632627435717632
stalk-surface-above-ring : 0.015010340962263224
stalk-surface-below-ring : 0.0758463077058795
stalk-color-above-ring : 0.02545853816960747
stalk-color-below-ring : 0.07289447740680202
veil-type : 0.0
veil-color : 0.023632627435717632
ring-number : 0.06673270290817772
ring-type : 0.007075382148931275
population : 0.026483962959073237
habitat : 0.08441395671019752
best feature -  habitat

cap-shape : 0.012982559278855665
cap-surface : 0.1747991377621008
cap-color : 0.054869684499314175
bruises : 0.0
gill-attachment : 0.0
gill-spacing : 0.0
gill-size : 0.3017832647462278
gill-color : 0.0
stalk-shape : 0.0
stalk-root : 0.0
stalk-surface-above-ring : 0.3017832647462278
stalk-surface-below-ring : 0.0
stalk-color-above-ring : 0.3017832647462278
stalk-color-below-ring : 0.04034535624949581
veil-type : 0.0
veil-color : 0.0
ring-number : 0.3017832647462278
ring-type : 0.3017832647462278
population : 0.3017832647462278
best feature -  gill-size

cap-shape : 0.19737891737891744
cap-surface : 0.15922705314009675
cap-color : 0.3911111111111112
bruises : 0.16547008547008554
gill-attachment : 0.0
gill-spacing : 0.0
gill-size : 0.0
gill-color : 0.07682539682539685
stalk-shape : 0.0
stalk-root : 0.16547008547008554
stalk-surface-above-ring : 0.19111111111111118
stalk-surface-below-ring : 0.19717171717171725
stalk-color-above-ring : 0.16547008547008554
stalk-color-below-ring : 0.3911111111111112
veil-type : 0.0
veil-color : 0.16547008547008554
ring-number : 0.0
ring-type : 0.16547008547008554
population : 0.3911111111111112
best feature -  cap-color

miscError:

cap-shape : 0.0448469926134365
cap-surface : 0.0627857896588111
cap-color : 0.0750967288075976
bruises : 0.22687302145620825
odor : 0.4667604642982765
gill-attachment : -5.551115123125783e-17
gill-spacing : 0.09444249032711927
gill-size : 0.23672177277523743
gill-color : 0.28895532887794584
stalk-shape : 0.03622933520928601
stalk-root : 0.11712979247274008
stalk-surface-above-ring : 0.2548364403798805
stalk-surface-below-ring : 0.24657052409426666
stalk-color-above-ring : 0.19943721421034122
stalk-color-below-ring : 0.19293000351741119
veil-type : 0.0
veil-color : 0.0010552233556102575
ring-number : 0.018818149841716536
ring-type : 0.2578262398874429
spore-print-color : 0.34857544846992616
population : 0.20471333098839256
habitat : 0.17235314808301094
best feature -  odor

cap-shape : 0.001214083367057868
cap-surface : 0.0016187778227437846
cap-color : 0.007284500202347211
bruises : -1.3877787807814457e-17
gill-attachment : 2.7755575615628914e-17
gill-spacing : -4.163336342344337e-17
gill-size : -2.7755575615628914e-17
gill-color : 0.007284500202347211
stalk-shape : -1.3877787807814457e-17
stalk-root : 0.0024281667341157186
stalk-surface-above-ring : -4.163336342344337e-17
stalk-surface-below-ring : 0.006070416835289347
stalk-color-above-ring : 0.002428166734115715
stalk-color-below-ring : 0.006475111290975315
veil-type : 0.0
veil-color : 0.00242816673411576
ring-number : -2.7755575615628914e-17
ring-type : -1.3877787807814457e-17
spore-print-color : 0.018615944961554002
population : 0.0
habitat : 0.009307972480777006
best feature -  spore-print-color

cap-shape : 0.006849315068493192
cap-surface : 0.009132420091324284
cap-color : 0.04109589041095896
bruises : 6.938893903907228e-17
gill-attachment : 0.0
gill-spacing : 6.938893903907228e-17
gill-size : 0.0022831050228311056
gill-color : 0.00684931506849322
stalk-shape : 0.0
stalk-root : 0.013698630136986398
stalk-surface-above-ring : 4.163336342344337e-17
stalk-surface-below-ring : 0.03424657534246579
stalk-color-above-ring : 0.013698630136986314
stalk-color-below-ring : 0.03652968036529687
veil-type : 0.0
veil-color : 0.013698630136986398
ring-number : 0.0022831050228311056
ring-type : 2.7755575615628914e-17
population : 2.7755575615628914e-17
habitat : 0.03881278538812789
best feature -  cap-color

cap-shape : 0.018348623853210982
cap-surface : 0.05504587155963303
bruises : 0.05504587155963303
gill-attachment : 0.0
gill-spacing : 0.0
gill-size : 0.05504587155963303
gill-color : -2.0816681711721685e-17
stalk-shape : 0.0
stalk-root : 0.0
stalk-surface-above-ring : 2.7755575615628914e-17
stalk-surface-below-ring : 6.938893903907228e-18
stalk-color-above-ring : 0.0
stalk-color-below-ring : 0.0
veil-type : 0.0
veil-color : 0.0
ring-number : 0.05504587155963303
ring-type : 0.0
population : 0.05504587155963303
habitat : 0.05504587155963303
best feature -  cap-surface

cap-shape : -1.3877787807814457e-17
cap-surface : 2.7755575615628914e-17
bruises : -1.3877787807814457e-17
gill-attachment : 0.0
gill-spacing : 0.0
gill-size : 1.3877787807814457e-17
gill-color : 0.0
stalk-shape : 0.0
stalk-root : 0.0
stalk-surface-above-ring : 0.12345679012345678
stalk-surface-below-ring : -1.3877787807814457e-17
stalk-color-above-ring : 1.3877787807814457e-17
stalk-color-below-ring : 0.04938271604938271
veil-type : 0.0
veil-color : 0.0
ring-number : 1.3877787807814457e-17
ring-type : 0.0
population : -1.3877787807814457e-17
habitat : 0.061728395061728385
best feature -  stalk-surface-above-ring

In [ ]:
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
def display(DeciTree):
  y_pred = []
  for i, row in X_test.iterrows():
    out= predict(row, DeciTree)
    y_pred.append(out)
  print(classification_report(y_test, y_pred))
  print(accuracy_score(y_test, y_pred))

In [ ]:
display(dt1)
display(dt2)
display(dt3)
display(dt4)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1256
           1       1.00      1.00      1.00      1182

    accuracy                           1.00      2438
   macro avg       1.00      1.00      1.00      2438
weighted avg       1.00      1.00      1.00      2438

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1256
           1       1.00      1.00      1.00      1182

    accuracy                           1.00      2438
   macro avg       1.00      1.00      1.00      2438
weighted avg       1.00      1.00      1.00      2438

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1256
           1       1.00      1.00      1.00      1182

    accuracy                           1.00      2438
   macro avg       1.00      1.00      1.00      2438
weighted avg       1.00      1.00      1.00      2438

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1256
           1       1.00      1.00      1.00      1182

    accuracy                           1.00      2438
   macro avg       1.00      1.00      1.00      2438
weighted avg       1.00      1.00      1.00      2438

1.0