<a href="https://colab.research.google.com/github/sidcodes2727/ML-labs/blob/main/MLlab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub
path = kagglehub.dataset_download("uciml/mushroom-classification")
path

Using Colab cache for faster access to the 'mushroom-classification' dataset.

'/kaggle/input/mushroom-classification'

In [ ]:
import pandas as pd
df = pd.read_csv("/kaggle/input/mushroom-classification/mushrooms.csv")
print(df.columns)
print(df.duplicated().sum())
print(df.isnull().sum())
for c in df.columns:
    print(c)
    print(df[c].unique())
    print()
df

Index(['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')
0
class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64
class
['p' 'e']

cap-shape
['x' 'b' 's' 'f' 'k' 'c']

cap-surface
['s' 'y' 'f' 'g']

cap-color
['n' 'y' 'w' 'g' 'e' 'p' 'b' 'u' 'c' 'r']

bruises
['t' 'f']

odor
['p' 'a' 'l' 'n' 'f' 'c' 'y' 's' 'm']

gill-attachment
['f' 'a']

gill-spacing
['c' 'w']

gill-size
['n' 'b']

gill-color
['k' 'n' 'g' 'p' 'w' 'h' 'u' 'e' 'b' 'r' 'y' 'o']

stalk-shape
['e' 't']

stalk-root
['e' 'c' 'b' 'r' '?']

stalk-surface-above-ring
['s' 'f' 'k' 'y']

stalk-surface-below-ring
['s' 'f' 'y' 'k']

stalk-color-above-ring
['w' 'g' 'p' 'n' 'b' 'e' 'o' 'c' 'y']

stalk-color-below-ring
['w' 'p' 'g' 'b' 'n' 'e' 'y' 'o' 'c']

veil-type
['p']

veil-color
['w' 'n' 'o' 'y']

ring-number
['o' 't' 'n']

ring-type
['p' 'e' 'l' 'f' 'n']

spore-print-color
['k' 'n' 'u' 'h' 'w' 'r' 'o' 'y' 'b']

population
['s' 'n' 'a' 'v' 'y' 'c']

habitat
['u' 'g' 'm' 'd' 'p' 'w' 'l']

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,e,k,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,b,c,l
8120,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,n,o,p,b,v,l
8121,e,f,s,n,f,n,a,c,b,n,...,s,o,o,p,o,o,p,b,c,l
8122,p,k,y,n,f,y,f,c,n,b,...,k,w,w,p,w,o,e,w,v,l
8123,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,o,c,l

In [ ]:
df["class"].value_counts()

class
e    4208
p    3916
Name: count, dtype: int64

In [ ]:
print(df["stalk-root"].mode())
req = df['stalk-root'].mode()[0]
df['stalk-root'] = df['stalk-root'].replace('?', req)
print(df['stalk-root'].unique())

0    b
Name: stalk-root, dtype: object
['e' 'c' 'b' 'r']

In [ ]:
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
for col in df.columns:
    df[col] = enc.fit_transform(df[col])
df

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,1,5,2,4,1,6,1,0,1,4,...,2,7,7,0,2,1,4,2,3,5
1,0,5,2,9,1,0,1,0,0,4,...,2,7,7,0,2,1,4,3,2,1
2,0,0,2,8,1,3,1,0,0,5,...,2,7,7,0,2,1,4,3,2,3
3,1,5,3,8,1,6,1,0,1,5,...,2,7,7,0,2,1,4,2,3,5
4,0,5,2,3,0,5,1,1,0,4,...,2,7,7,0,2,1,0,3,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,0,3,2,4,0,5,0,0,0,11,...,2,5,5,0,1,1,4,0,1,2
8120,0,5,2,4,0,5,0,0,0,11,...,2,5,5,0,0,1,4,0,4,2
8121,0,2,2,4,0,5,0,0,0,5,...,2,5,5,0,1,1,4,0,1,2
8122,1,3,3,4,0,8,1,0,1,0,...,1,7,7,0,2,1,0,7,4,2
8123,0,5,2,4,0,5,0,0,0,11,...,2,5,5,0,1,1,4,4,1,2

In [ ]:
from sklearn.model_selection import train_test_split
X= df.drop(columns=['class'])
y= df['class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(5686, 22)
(2438, 22)
(5686,)
(2438,)

In [ ]:
from sklearn.naive_bayes import CategoricalNB
model = CategoricalNB()
model.fit(X_train,y_train)
y_pred= model.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, accuracy_score
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9520098441345365
              precision    recall  f1-score   support

           0       0.92      0.99      0.96      1306
           1       0.99      0.90      0.95      1132

    accuracy                           0.95      2438
   macro avg       0.96      0.95      0.95      2438
weighted avg       0.96      0.95      0.95      2438

In [ ]:
def calc(y_train):
  tot = len(y_train)
  pedible=0
  ppoi=0
  for c in y_train:
    if c==0:
      pedible+=1
    else:
      ppoi+=1

  return pedible/tot,ppoi/tot

In [ ]:
def conditionalProb(X_train,y_train,feature,value,c):
    sub= X_train[y_train==c]
    cnt= sum(sub[feature]==value)
    tot= len(sub)
    k= X_train[feature].nunique()
    p= (cnt+1)/(tot+k)

    return p

In [ ]:
def predict(inp):
  pedible, ppoi = calc(y_train)
  for fea in X_train.columns:
    val= inp[fea]
    pedible*=conditionalProb(X_train,y_train,fea,val,0)
    ppoi*=conditionalProb(X_train,y_train,fea,val,1)
  if pedible> ppoi:
    return 0

  return 1

In [ ]:
y_pred=[]
for i,row in X_test.iterrows():
  out= predict(row)
  y_pred.append(out)

In [ ]:
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.99      0.96      1277
           1       0.99      0.91      0.95      1161

    accuracy                           0.95      2438
   macro avg       0.96      0.95      0.95      2438
weighted avg       0.96      0.95      0.95      2438

0.9528301886792453