<a href="https://colab.research.google.com/github/sidcodes2727/ML-labs/blob/main/MLlab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub
path = kagglehub.dataset_download("uciml/mushroom-classification")
path

Using Colab cache for faster access to the 'mushroom-classification' dataset.

'/kaggle/input/mushroom-classification'

In [ ]:
import pandas as pd
df = pd.read_csv('/kaggle/input/mushroom-classification/mushrooms.csv')
print(df.columns)
print(df.duplicated().sum())
for c in df.columns:
    print(c)
    print(df[c].unique())
    print()
df

Index(['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')
0
class
['p' 'e']

cap-shape
['x' 'b' 's' 'f' 'k' 'c']

cap-surface
['s' 'y' 'f' 'g']

cap-color
['n' 'y' 'w' 'g' 'e' 'p' 'b' 'u' 'c' 'r']

bruises
['t' 'f']

odor
['p' 'a' 'l' 'n' 'f' 'c' 'y' 's' 'm']

gill-attachment
['f' 'a']

gill-spacing
['c' 'w']

gill-size
['n' 'b']

gill-color
['k' 'n' 'g' 'p' 'w' 'h' 'u' 'e' 'b' 'r' 'y' 'o']

stalk-shape
['e' 't']

stalk-root
['e' 'c' 'b' 'r' '?']

stalk-surface-above-ring
['s' 'f' 'k' 'y']

stalk-surface-below-ring
['s' 'f' 'y' 'k']

stalk-color-above-ring
['w' 'g' 'p' 'n' 'b' 'e' 'o' 'c' 'y']

stalk-color-below-ring
['w' 'p' 'g' 'b' 'n' 'e' 'y' 'o' 'c']

veil-type
['p']

veil-color
['w' 'n' 'o' 'y']

ring-number
['o' 't' 'n']

ring-type
['p' 'e' 'l' 'f' 'n']

spore-print-color
['k' 'n' 'u' 'h' 'w' 'r' 'o' 'y' 'b']

population
['s' 'n' 'a' 'v' 'y' 'c']

habitat
['u' 'g' 'm' 'd' 'p' 'w' 'l']

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,e,k,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,b,c,l
8120,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,n,o,p,b,v,l
8121,e,f,s,n,f,n,a,c,b,n,...,s,o,o,p,o,o,p,b,c,l
8122,p,k,y,n,f,y,f,c,n,b,...,k,w,w,p,w,o,e,w,v,l
8123,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,o,c,l

In [ ]:
df["class"].value_counts()

class
e    4208
p    3916
Name: count, dtype: int64

In [ ]:
print(df["stalk-root"].mode())
req = df['stalk-root'].mode()[0]
df['stalk-root'] = df['stalk-root'].replace('?', req)
print(df['stalk-root'].unique())

0    b
Name: stalk-root, dtype: object
['e' 'c' 'b' 'r']

In [ ]:
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
for col in df.columns:
    df[col] = enc.fit_transform(df[col])
df

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,1,5,2,4,1,6,1,0,1,4,...,2,7,7,0,2,1,4,2,3,5
1,0,5,2,9,1,0,1,0,0,4,...,2,7,7,0,2,1,4,3,2,1
2,0,0,2,8,1,3,1,0,0,5,...,2,7,7,0,2,1,4,3,2,3
3,1,5,3,8,1,6,1,0,1,5,...,2,7,7,0,2,1,4,2,3,5
4,0,5,2,3,0,5,1,1,0,4,...,2,7,7,0,2,1,0,3,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,0,3,2,4,0,5,0,0,0,11,...,2,5,5,0,1,1,4,0,1,2
8120,0,5,2,4,0,5,0,0,0,11,...,2,5,5,0,0,1,4,0,4,2
8121,0,2,2,4,0,5,0,0,0,5,...,2,5,5,0,1,1,4,0,1,2
8122,1,3,3,4,0,8,1,0,1,0,...,1,7,7,0,2,1,0,7,4,2
8123,0,5,2,4,0,5,0,0,0,11,...,2,5,5,0,1,1,4,4,1,2

In [ ]:
from sklearn.model_selection import train_test_split
X= df.drop(columns=['class'])
y= df['class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(5686, 22)
(2438, 22)
(5686,)
(2438,)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
model.score(X_test, y_test)

1.0

In [ ]:
from sklearn.metrics import classification_report
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1253
           1       1.00      1.00      1.00      1185

    accuracy                           1.00      2438
   macro avg       1.00      1.00      1.00      2438
weighted avg       1.00      1.00      1.00      2438

In [ ]:
import numpy as np
def entropy(fea):
  # fea.value_counts()
  cnts= fea.value_counts()
  tot= len(fea)
  req= 0;
  for i in cnts:
    p=i/tot
    req=req-p*np.log2(p)

  return req
# entropy(df['class'])

In [ ]:
def infoGain(data, fea):
  parentEntropy = entropy(data['class'])
  sumchildEntropy = 0
  for i in data[fea].unique():
    req = data[data[fea] == i]
    prop = len(req)/len(data)
    sumchildEntropy+= prop* entropy(req['class'])

  return parentEntropy - sumchildEntropy

In [ ]:
features= list(df.columns)
features.remove('class')

for feature in features:
    print(feature,":", infoGain(df, feature))

cap-shape : 0.048796701935373
cap-surface : 0.028590232773772706
cap-color : 0.0360492829762038
bruises : 0.19237948576121955
odor : 0.9060749773839998
gill-attachment : 0.014165027250616191
gill-spacing : 0.10088318399657026
gill-size : 0.23015437514804604
gill-color : 0.41697752341613126
stalk-shape : 0.00751677256966421
stalk-root : 0.10834857380797513
stalk-surface-above-ring : 0.2847255992184844
stalk-surface-below-ring : 0.2718944733927463
stalk-color-above-ring : 0.2538451734622398
stalk-color-below-ring : 0.24141556652756646
veil-type : 0.0
veil-color : 0.02381701612091669
ring-number : 0.03845266924309043
ring-type : 0.3180215107935376
spore-print-color : 0.4807049176849153
population : 0.2019580190668523
habitat : 0.1568336046050921

In [ ]:
def id3(data, features):
    if entropy(data['class'])==0: return data['class'].iloc[0]

    if len(features)==0:  return data['class'].mode()[0]
    gains=[]

    for f in features:
        temp = infoGain(data,f)
        print(f"{f} :", temp)
        gains.append(temp)

    idx = np.argmax(gains)
    bestFeature = features[idx]
    print(f"best feature - ", bestFeature)
    print()
    tree = {bestFeature:{}}

    remFeatures= []
    for f in features:
      if f!=bestFeature:
        remFeatures.append(f)

    for val in data[bestFeature].unique():
        filter= data[data[bestFeature]==val]
        tree[bestFeature][val]= id3(filter,remFeatures)

    return tree

In [ ]:
def predict(query, tree):

    for node in tree.keys():
        value= query[node]
        res= tree[node][value]

        if isinstance(res,dict):
            return predict(query, res)
        else:
            return res

In [ ]:
train_df = X_train.copy()
train_df["class"] = y_train
features = list(X_train.columns)
DeciTree = id3(train_df, features)

cap-shape : 0.049621789338401556
cap-surface : 0.028597845453195214
cap-color : 0.03422112356247664
bruises : 0.195295964817766
odor : 0.9145322605687756
gill-attachment : 0.012799118725125735
gill-spacing : 0.10099060551912864
gill-size : 0.2324537529633749
gill-color : 0.42091777371677186
stalk-shape : 0.00696704824950678
stalk-root : 0.10882713100503949
stalk-surface-above-ring : 0.28648058249202535
stalk-surface-below-ring : 0.27646470906882725
stalk-color-above-ring : 0.25428216925563885
stalk-color-below-ring : 0.24026572928876544
veil-type : 0.0
veil-color : 0.022332777188844632
ring-number : 0.04109647795115967
ring-type : 0.3199735836235592
spore-print-color : 0.4771178988536764
population : 0.19856309881905843
habitat : 0.15213165811992524
best feature -  odor

cap-shape : 0.036701505184559
cap-surface : 0.01310166396421314
cap-color : 0.08103751115809169
bruises : 0.0003071444512206811
gill-attachment : 0.0023192895031483862
gill-spacing : 0.003998533885772287
gill-size : 0.02354995915848465
gill-color : 0.07854097676867751
stalk-shape : 0.05550726346132159
stalk-root : 0.021804714081076954
stalk-surface-above-ring : 0.023597774363769003
stalk-surface-below-ring : 0.04999618171551479
stalk-color-above-ring : 0.032242453994258596
stalk-color-below-ring : 0.05746090663350931
veil-type : 0.0
veil-color : 0.012510474136414512
ring-number : 0.018514644624166493
ring-type : 0.001036818173259152
spore-print-color : 0.12719516437177414
population : 0.038229040658968455
habitat : 0.05932634432433073
best feature -  spore-print-color

cap-shape : 0.027224405261948803
cap-surface : 0.07927480285676508
cap-color : 0.20137146163328182
bruises : 0.01200091126909092
gill-attachment : 0.0
gill-spacing : 0.015124663061936827
gill-size : 0.21752601982403616
gill-color : 0.0856049787128535
stalk-shape : 0.0
stalk-root : 0.04416681144340212
stalk-surface-above-ring : 0.0701020086347951
stalk-surface-below-ring : 0.214550932000595
stalk-color-above-ring : 0.0632339006453444
stalk-color-below-ring : 0.19805360770813918
veil-type : 0.0
veil-color : 0.04416681144340212
ring-number : 0.21752601982403616
ring-type : 0.037291674239347095
population : 0.11044799984702736
habitat : 0.2585395233132831
best feature -  habitat

cap-shape : 0.2766341921408615
cap-surface : 0.2559352276912261
cap-color : 0.7382848661434506
bruises : 0.27373281474975997
gill-attachment : 0.0
gill-spacing : 0.0
gill-size : 0.0
gill-color : 0.153687795943953
stalk-shape : 0.0
stalk-root : 0.27373281474975997
stalk-surface-above-ring : 0.3838893070949514
stalk-surface-below-ring : 0.3763341476244326
stalk-color-above-ring : 0.27373281474975997
stalk-color-below-ring : 0.7382848661434506
veil-type : 0.0
veil-color : 0.27373281474975997
ring-number : 0.0
ring-type : 0.27373281474975997
population : 0.7382848661434506
best feature -  cap-color

cap-shape : 0.03625683088144971
cap-surface : 0.4283898022309328
cap-color : 0.12013411808852814
bruises : 0.0
gill-attachment : 0.0
gill-spacing : 0.0
gill-size : 0.6193821946787638
gill-color : 0.0
stalk-shape : 0.0
stalk-root : 0.0
stalk-surface-above-ring : 0.6193821946787638
stalk-surface-below-ring : 0.0
stalk-color-above-ring : 0.6193821946787638
stalk-color-below-ring : 0.13670484355885965
veil-type : 0.0
veil-color : 0.0
ring-number : 0.6193821946787638
ring-type : 0.6193821946787638
population : 0.6193821946787638
best feature -  gill-size

In [ ]:
DeciTree

{'odor': {np.int64(5): {'spore-print-color': {np.int64(3): np.int64(0),
    np.int64(2): np.int64(0),
    np.int64(4): np.int64(0),
    np.int64(7): {'habitat': {np.int64(1): np.int64(0),
      np.int64(6): np.int64(0),
      np.int64(2): {'cap-color': {np.int64(4): np.int64(0),
        np.int64(8): np.int64(1),
        np.int64(1): np.int64(0),
        np.int64(9): np.int64(1)}},
      np.int64(4): np.int64(0),
      np.int64(0): {'gill-size': {np.int64(1): np.int64(1),
        np.int64(0): np.int64(0)}}}},
    np.int64(1): np.int64(0),
    np.int64(8): np.int64(0),
    np.int64(0): np.int64(0),
    np.int64(5): np.int64(1)}},
  np.int64(2): np.int64(1),
  np.int64(3): np.int64(0),
  np.int64(7): np.int64(1),
  np.int64(6): np.int64(1),
  np.int64(8): np.int64(1),
  np.int64(1): np.int64(1),
  np.int64(4): np.int64(1),
  np.int64(0): np.int64(0)}}

In [ ]:
y_pred = []

for i, row in X_test.iterrows():
  out= predict(row, DeciTree)
  y_pred.append(out)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1253
           1       1.00      1.00      1.00      1185

    accuracy                           1.00      2438
   macro avg       1.00      1.00      1.00      2438
weighted avg       1.00      1.00      1.00      2438